2025-06-27 15:12:35> 已从配置加载: 2 个虚拟目录
2025-06-27 15:12:36> 服务器已启动: http://0.0.0.0:8000
2025-06-27 15:12:37> 服务器启动(多线程模式): http://0.0.0.0:8000
2025-06-27 15:12:37> 根目录: C:/Users/Administrator/Desktop/python-pro
2025-06-27 15:12:41> 192.168.100.4:51377- code 404, message File not found
2025-06-27 15:12:41> 192.168.100.4:51377- "GET /upload HTTP/1.1" 404 -
2025-06-27 15:12:43> 192.168.100.4:51378- "GET / HTTP/1.1" 200 -
2025-06-27 15:12:45> 192.168.100.4:51378- "GET /login HTTP/1.1" 200 -
2025-06-27 15:12:46> 192.168.100.4:51387- "POST /login HTTP/1.1" 302 -
2025-06-27 15:12:46> 192.168.100.4:51387- 用户认证成功，用户名admin,session:404099086cf2fb62fc70862592da4f88
2025-06-27 15:12:46> 192.168.100.4:51389- "GET / HTTP/1.1" 200 -
2025-06-27 15:12:51> 192.168.100.4:51390- code 500, message Upload processing failed: cannot access local variable 'target_path' where it is not associated with a value
2025-06-27 15:12:51> 192.168.100.4:51390- "POST /upload HTTP/1.1" 500 -
